"""Add skipped task status

Revision ID: 0c20bd56b97d
Revises: 7b63dccc9152
Create Date: 2025-07-13 06:40:07.224195

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0c20bd56b97d"
down_revision = "7b63dccc9152"
branch_labels = None
depends_on = None

enum_name = "taskstatus"


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("posts", "download_duration")

  op.execute(f"ALTER TYPE {enum_name} ADD VALUE IF NOT EXISTS 'skipped'")
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "posts",
    sa.Column(
      "download_duration",
      postgresql.INTERVAL(),
      autoincrement=False,
      nullable=True,
    ),
  )
  # ### end Alembic commands ###
