"""add user_id to task model

Revision ID: 26587620f3e7
Revises: 0c20bd56b97d
Create Date: 2025-07-27 11:28:16.493810

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "26587620f3e7"
down_revision = "0c20bd56b97d"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("tasks", sa.Column("user_id", sa.Uuid(), nullable=True))
  op.alter_column(
    "tasks",
    "created_at",
    existing_type=postgresql.TIMESTAMP(),
    type_=sa.TIMESTAMP(timezone=True),
    existing_nullable=False,
  )
  op.create_index(op.f("ix_tasks_user_id"), "tasks", ["user_id"], unique=False)
  op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"])
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "tasks", type_="foreignkey")
  op.drop_index(op.f("ix_tasks_user_id"), table_name="tasks")
  op.alter_column(
    "tasks",
    "created_at",
    existing_type=sa.TIMESTAMP(timezone=True),
    type_=postgresql.TIMESTAMP(),
    existing_nullable=False,
  )
  op.drop_column("tasks", "user_id")
  # ### end Alembic commands ###
