"""initialise models

Revision ID: 7b63dccc9152
Revises:
Create Date: 2025-07-12 18:32:43.140194

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7b63dccc9152"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "authors",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("username", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "generation_metadata",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column(
      "model_used",
      sa.Text(),
      nullable=False,
      comment="The AI model used for generation (e.g., Gemini 2.5 Pro, Flash)",
    ),
    sa.Column("prompt_token_count", sa.Integer(), nullable=False),
    sa.Column("candidates_token_count", sa.Integer(), nullable=False),
    sa.Column("total_token_count", sa.Integer(), nullable=False),
    sa.Column("analysis_duration_ms", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "languages",
    sa.Column("id", sa.String(length=2), nullable=False),
    sa.Column(
      "name",
      sa.String(length=64),
      nullable=False,
      comment='e.g., "English", "Spanish"',
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "users",
    sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column("is_active", sa.Boolean(), nullable=False),
    sa.Column("is_superuser", sa.Boolean(), nullable=False),
    sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
  op.create_table(
    "posts",
    sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("author_id", sa.Uuid(), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("taken_at", sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column("download_duration", sa.Interval(), nullable=True),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["author_id"], ["authors.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_posts_id"), "posts", ["id"], unique=False)
  op.create_table(
    "images",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("post_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("storage_key", sa.Text(), nullable=False),
    sa.Column("height", sa.Integer(), nullable=False),
    sa.Column("width", sa.Integer(), nullable=False),
    sa.Column(
      "is_primary",
      sa.Boolean(),
      nullable=False,
      comment="To mark the main image of a carousel",
    ),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id"),
    sa.UniqueConstraint("storage_key"),
  )
  op.create_table(
    "compliments",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("image_id", sa.Uuid(), nullable=False),
    sa.Column("lang_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("generation_id", sa.Uuid(), nullable=False),
    sa.Column("text", sa.Text(), nullable=False),
    sa.Column("tone_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(
      ["generation_id"], ["generation_metadata.id"], ondelete="RESTRICT"
    ),
    sa.ForeignKeyConstraint(["image_id"], ["images.id"], ondelete="CASCADE"),
    sa.ForeignKeyConstraint(["lang_id"], ["languages.id"], ondelete="RESTRICT"),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_table(
    "tasks",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column(
      "type",
      sa.Enum("llm_generate", "instagram_download", name="tasktype"),
      nullable=False,
    ),
    sa.Column(
      "status",
      sa.Enum("pending", "in_progress", "done", "failed", name="taskstatus"),
      nullable=False,
    ),
    sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("started_at", sa.DateTime(), nullable=True),
    sa.Column("ended_at", sa.DateTime(), nullable=True),
    sa.Column("duration", sa.Interval(), nullable=True),
    sa.Column("post_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("image_id", sa.Uuid(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(
      ["image_id"],
      ["images.id"],
    ),
    sa.ForeignKeyConstraint(
      ["post_id"],
      ["posts.id"],
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
  op.drop_table("tasks")
  op.drop_table("compliments")
  op.drop_table("images")
  op.drop_index(op.f("ix_posts_id"), table_name="posts")
  op.drop_table("posts")
  op.drop_index(op.f("ix_users_email"), table_name="users")
  op.drop_table("users")
  op.drop_table("languages")
  op.drop_table("generation_metadata")
  op.drop_table("authors")
  # ### end Alembic commands ###
