"""add user_id to post model

Revision ID: 9675e4a0eb4b
Revises: 26587620f3e7
Create Date: 2025-07-27 15:18:42.764737

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9675e4a0eb4b"
down_revision = "26587620f3e7"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column("posts", sa.Column("user_id", sa.Uuid(), nullable=True))
  op.create_foreign_key(
    None, "posts", "users", ["user_id"], ["id"], ondelete="RESTRICT"
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_constraint(None, "posts", type_="foreignkey")
  op.drop_column("posts", "user_id")
  # ### end Alembic commands ###
